---
# This role starts a nginx component

- name: ensure nginx config directory exists
  file:
    path: "{{ nginx_conf_dir }}"
    state: directory

- name: copy template from local to remote in nginx config directory
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/nginx.conf"

- name: copy cert files from local to remote in nginx config directory
  copy:
    src: "files/"
    dest: "{{ nginx_conf_dir }}"

- name: create configmap
  shell: "kubectl create configmap nginx --from-file={{ nginx_conf_dir }}/nginx.conf --from-file={{ nginx_conf_dir }}/genssl.sh --from-file={{ nginx_conf_dir }}/openwhisk-key.pem --from-file={{ nginx_conf_dir }}/openwhisk-cert.pem --from-file={{ nginx_conf_dir }}/openwhisk-request.csr"

- name: create nginx pod
  shell: "kubectl create -f {{kube_pod_dir}}/nginx.yml"

# TODO Rebplace this with a proper uri request once certs have been configured correctly
- name: wait until nginx is up and running
  shell: "curl -k https://{{ nginx_host }}:{{ nginx.port.api }}"
  register: result
  until: (result.rc == 0) and (result.stdout != "")
  retries: 20
  delay: 10

